---
version: '3.9'
services:
    router:
        container_name: router
        image: 10.64.38.13:5000/raikou-router
        ports:
            - 4000:22
        environment:
            ENABLE_NAT_ON: eth0
            FRR_AUTO_CONF: yes # yamllint disable-line rule:truthy
            TRIPLE_PLAY: yes # yamllint disable-line rule:truthy
            CPE_MGMT_IFACE: vl_eth1
            CPE_DATA_IFACE: vl_eth2
            CPE_VOICE_IFACE: vl_eth3
            CPE_MGMT_BUNDLE: 10.1.1.1/24,2001:dead:cafe:1::1/64
            CPE_DATA_BUNDLE: 10.1.2.1/24,2001:dead:cafe:2::1/64
            CPE_VOICE_BUNDLE: 10.1.3.1/24,2001:dead:cafe:3::1/64
            MCAST_TARGET: vl_eth2
            DHCP_RELAY: eth1,172.25.1.20,2001:dead:beef:2::20

        privileged: true
        hostname: router
        depends_on:
            - ssh_service

    wan:
        container_name: wan
        image: 10.64.38.13:5000/raikou-wan
        ports:
            - 4001:22
        environment:
            DNS_UPSTREAM: 172.30.180.2
            LEGACY: no # yamllint disable-line rule:truthy
        privileged: true
        hostname: wan
        depends_on:
            - ssh_service

    lan:
        container_name: lan
        image: 10.64.38.13:5000/raikou-lan
        ports:
            - 4002:22
        environment:
            LEGACY: no # yamllint disable-line rule:truthy
        privileged: true
        hostname: lan
        depends_on:
            - ssh_service

    dhcp:
        container_name: dhcp
        image: 10.64.38.13:5000/raikou-dhcp
        ports:
            - 4003:22
        environment:
            LEGACY: no # yamllint disable-line rule:truthy
        privileged: true
        hostname: dhcp
        depends_on:
            - ssh_service

    mongo:
        image: 10.64.38.13:5000/mongo:4.4
        restart: always
        privileged: true
        container_name: mongo
        hostname: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=bigfoot1
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/var/log/mongodb
        volumes:
            - data_db:/data/db
            - data_configdb:/data/configdb
        ports:
            - 27017:27017

    acs:
        depends_on:
            - mongo
        image: 10.64.38.13:5000/raikou-acs
        restart: always
        container_name: acs
        hostname: acs
        environment:
            - GENIEACS_UI_JWT_SECRET=bigfoot1
            - GENIEACS_CWMP_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-cwmp-access.log
            - GENIEACS_NBI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-nbi-access.log
            - GENIEACS_FS_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-fs-access.log
            - GENIEACS_UI_ACCESS_LOG_FILE=/var/log/genieacs/genieacs-ui-access.log
            - GENIEACS_DEBUG_FILE=/var/log/genieacs/genieacs-debug.yaml
            - GENIEACS_EXT_DIR=/opt/genieacs/ext
            - GENIEACS_MONGODB_CONNECTION_URL=mongodb://admin:bigfoot1@mongo:27017
        privileged: true
        ports:
            - 4503:22
            - 7547:7547
            - 7557:7557
            - 7567:7567
            - 3000:3000
        volumes:
            - opt_volume:/opt

    raikou-net:
        container_name: orchestrator
        image: 10.64.38.13:5000/raikou-net
        volumes:
            - /lib/modules:/lib/modules
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config.json:/root/config.json
        privileged: true
        pid: host
        network_mode: host
        hostname: orchestrator
        depends_on:
            - router
            - wan
            - lan
            - dhcp
            - acs

    ssh_service:
        image: 10.64.38.13:5000/raikou-ssh

networks:
    default:
        ipam:
            config:
                - subnet: 192.168.55.0/24
                  gateway: 192.168.55.1
